### ISSUE TITLE
PROJECTS missing descriptions

### ISSUE THREAD

**Issue by katiesaunders** [MFEh2o/db#15]
Descriptions have not been filled in since projectID 17.

**Comment by kaijagahm** [comment]
Created a google doc containing attempts to dig up metadata files and infer descriptions from them. Was successful for some. Need @joneslabND @ctsolomon @Randinotte to either help fill out descriptions or help connect me with people who were in charge of these projects.

Two other thoughts:
1. The project names sometimes, but not always, list the name of the person in charge and the year the project was conducted. This seems like useful information. Could we add it to the table in separate columns? Maybe one column for the name of the person in charge, one column for the start year, one column for the end year?

2. Ditto the metadata files: I've been having trouble digging them up, since I have to go through each individual table, see if it has samples from that project, and then see if the metadata file gives any sort of description of the project as a whole. Could we have a column here that provides the name of the sort of "overarching" metadata file, project proposal, etc. that describes the purpose and goals of the project, rather than nitty-gritty sampling procedures (which sometimes apply to other projects as well)?

**Comment by ctsolomon** [comment]
I added to the Google doc with some contact info, filled in some missing descriptions, and left comment bubbles on a couple of your questions. There are some rows that Stuart will do a better job filling out. Let me know if there are things that I missed or if you need more info.

Re listing person in charge etc. - yes, this seems like a good idea. Maybe we want a column for "project lead" and another for "responsible PI", so that when a student moves on to other things and ceases to be responsive we still know who to go to with questions. I think start year is also useful. I am not sure about end year - that seems like more of a headache to track and update accurately, but others could weigh in on this.

Re overarching metadata file - I'm curious to see what Stuart and Randi think about this. I think my inclination is not to force ourselves to include a file like that here, but instead rely on the "project description" column to remind us what a project was about.

**Comment by kaijagahm** [comment]
Sounds good. I'll add columns for "projectLead", "startYear", and "responsiblePI". I don't feel strongly at all about endYear! Just suggested start/end as an alternative to simply "year" because I knew there were many multi-year projects. But I think you're right that if we specify startYear that should be clear enough.

Re: metadata--my idea here wasn't necessarily to force the inclusion of a file that doesn't exist, but rather to provide a place to link to one if it does. My thinking was that there's currently a table set up for metadata for samples, but there's no straightforward way to use the database to learn about projects more generally. That might be fine––maybe we don't want people to use the database for that, and we'd like to instead focus on an alternative method of documenting projects. But it seemed to me that as long as we have a PROJECTS table and have developed the system of project numbers, it might make sense to use PROJECTS to point to additional information, on the project-wide level, if it exists.

But yes, @Randinotte @joneslabND would definitely like to hear your thoughts on this!

**Comment by kaijagahm** [comment]
Added projectLead, startYear, and responsiblePI. Began filling in that information, as well as project descriptions, drawing on metadata and suggestions from @Randinotte and @ctsolomon. Emailed Patrick Kelly to try to get information/metadata about projects 16 and 20 (his projects). 

Revamped the color-coding on the spreadsheet. Blue is "was already present in original database, and doesn't need to be changed". Red is "needs information". Yellow is "I've filled this in, but I'm not totally sure it's right." Green is "filled in and sure/confirmed; ready for update."

https://docs.google.com/spreadsheets/d/1BbINns77KriHZu2GpO-SVxO4SJX5JmokO3Sdpv61_bw/edit?usp=sharing

**Comment by joneslabND** [comment]
@kaijagahm @ctsolomon I like the addition of these columns and I'll add to the google doc where needed. I also don't think we need a project metadata file, but think we might add to the project yearbook with a page for each project with some basic template information or an abstract. This wouldn't necessarily be a public facing document, but would be useful for Chris and I as we lose our memory.

**Comment by kaijagahm** [comment]
@joneslabND I think that's a great idea. @Randinotte and I have been talking about doing something along those lines, as well. When you say "the project yearbook," are you talking about the MFE yearbook that already lists crew names, or is there a different project yearbook somewhere? In any case, let's discuss on Tuesday what format this can take and how we should approach creating it.

**Comment by kaijagahm** [comment]
PROJECTS is almost fully updated! Waiting on descriptions from Patrick for 16 and 20. Waiting on an update from Carly for 31. I'm meeting with Brittni on Friday, so should be able to get descriptions then for 34 and 35. Waiting on a description for 37 from Colin (Slack: https://mfe-hq.slack.com/archives/CH63N1C4X/p1593113506001500).

@joneslabND should I email Will West about a description for 18, "Will's Stuff 2013" (I'd need his address, if so) or can you write something/point me to a file? 

I'm still missing start years for several projects. If the year isn't obvious, the plan is to find the samples associated with that project and take the earliest year. The projects still missing years are 6, 8, 16 and 20 (ask Patrick), 17, 23, 27, 30, 31 (ask Carly), 32, 34 and 35 (ask Brittni), 37 and 38 (ask Colin), and 40.

**Comment by kaijagahm** [comment]
Still waiting on descriptions for 16 and 20, but otherwise the PROJECTS table is complete! 

At meeting 6/30/2020, Stuart decided that preserving the order of project numbers is important. 10 was missing, and there's no data associated with it in the database--I've added a new row for Project 10 and set it to NA. I've made a note in the description column of both 10 and 33 that these were created but never used, and should _not_ be used by someone else in the future, to preserve the order of projects.

**Comment by kaijagahm** [comment]
Still waiting on 16 and 20.

@joneslabND I added some notes to the top of the MFE yearbook document, along the lines of what it would be useful to see in a project "abstract". I hope that's helpful, and let me know if I can do anything else on that front!

**Comment by kaijagahm** [comment]
Stuart helped me add brief descriptions for the two Patrick projects (16 and 20) that I was still missing. We got all others filled in. The two bits of unfinished business related to this issue are #55 (abstracts) and #52 (need to link to data repos for several projects). This is enough of an update for now, though.
