### ISSUE TITLE
CREW needs updated information since 2014

### ISSUE THREAD

**Issue by katiesaunders** [MFEh2o/db#16]

**Comment by Randinotte** [comment]
Stuart et al. has created an "UNDERC yearbook" that's available on Google Drive. I have started an updated csv of the CREW table (attached). Stopped because we were still putting together the yearbook, haven't gone back. 
https://docs.google.com/document/d/1X0KHVqJDaWTPAic4lZbhgV5ZGKKQqM1lyBtNRLLAUg4/edit#heading=h.nvua3bp0rsbb
[crew_fix.xlsx](https://github.com/MFEh2o/db/files/4696250/crew_fix.xlsx)

**Comment by kaijagahm** [comment]
At Chris's suggestion, added a column for PI's (pis). Took the information in the MFE Yearbook as referring to semester == "Summer". Modified crew_fix.xlsx to add PI's, grad students, and undergrads. Assumed location == "UNDERC" for all of the yearbook additions, but emailed Chris, Randi, and Stuart to check that this is correct.

Other fixes in this version of the excel doc:
 - Standardized nickname syntax: Firstname (Nickname) Lastname, instead of Firstname "Nickname" Lastname––according to the database manual, we can't use double quotes in the database tables **[check on this]**. 
- Added nicknames or full names for students where only one was listed, bringing all names into compliance with this format.

NOTE: did _not_ delete any information from crew_fix.xlsx that wasn't contained in the yearbook. There will be a separate question about whether information needs to be added to the yearbook. However, did make one note about possibly deleting one technician's name from the excel sheet because she wasn't listed in the yearbook. **[check]**

Started to convert these manual changes into R code, but with the data in wide format, this is labor intensive and actually slower than doing the fixes by hand in excel. I will still do it if we want that for documentation purposes, but wanted to wait before continuing in case we decide to convert to long (see below).

Notes/thoughts/suggestions
- Consider converting to long format so that cells contain only one value
- If we do that: consider adding a column for nickname and for affiliation.

**Comment by kaijagahm** [comment]
Began to normalize the file, and got most of the way through. Not sure what to do about the updateID's, and need to check on row numbers.

There's still one name (Caceres-Velasquez or Caceres-Velazquez) that has two possible spellings. And we should still discuss whether we like this format or no.

**Comment by kaijagahm** [comment]
Fully reformatted file. Chris notes, rightly, that now we don't have a primary key. I note additionally that people's names are repeated. So this still isn't ideal. Technically we should have a separate PEOPLE table, and then crew would only have the ID numbers. But we've decided that that's more complicated than it's worth. Have passed the new-format table off to Randi/Chris/Stuart for additions of affiliations/nicknames/other info.

**Comment by kaijagahm** [comment]
Discussed this with Chris and confirmed with Stuart: having a separate PEOPLE table is going to be overkill for our purposes. We don't mind that there's no primary key. Retained original ID from the table (unique combo of year, semester, and location [i think?]), so that will now be a non-unique ID with the new format of the table. Chris added affiliations etc. to the table, and I joined them in. CREW has been exported as a txt file and is awaiting db update.

**Comment by kaijagahm** [comment]
Version 3.3.0 is live!

**Comment by kaijagahm** [comment]
Here is an Excel version of the interactive google spreadsheet I used for this update. Cleaning out my google drive and putting it here instead.
[CREW_newformat.xlsx](https://github.com/MFEh2o/db/files/6679325/CREW_newformat.xlsx)
