### ISSUE TITLE
Jones lake experiment data 2020

### ISSUE THREAD

**Issue by camillemosley** [MFEh2o/db#161]
The data uploaded to the database for summer 2020 for the jones lake experiment has some errors that need to be corrected. Many files in the fish info/samples tables are incorrect because of tag rounding errors. Those sheets must be deleted fixed and added before uploading all of 2021 project 41 data to FISH tables.

**Comment by Randinotte** [comment]
Update for @cwbeltz's notes: To get the ball rolling for Camille and Stuart to fix the fish entry tool, I removed all projectID 41 data (Jones Lake Experiment) from FISH_SAMPLES and FISH_DATA. This was accomplished in v.5.2.0. The data was not replaced because the team was just getting started on entry tool fixes. Once the tools are working, data for the whole project needs to be added.

**Comment by cwbeltz** [comment]
Cleaned and corrected Jones lake data uploaded along with data from project 42 (LMB Hook Memory).
