### ISSUE TITLE
incorrect time FISH_SAMPLES

### ISSUE THREAD

**Issue by ctsolomon** [MFEh2o/db#163]
Amaryllis has been checking field data sheets to answer queries that have arisen as I have been cleaning up Long tag data. She noticed that for sampleID 'WL_WholeShoreline_20170521_1230_BE_MarkRecap.20120228', the dateTimeSample should have been entered in database as 2017-05-21 00:30:00 (not as ...12:30:00). This will also require an update to the sampleID, since that contains the dateTimeSample.

**Comment by ctsolomon** [comment]
Similarly, Amaryllis says that for sampleID 'EL_WholeShoreline_20120612_0740_AN_MarkRecap.20120228', dateTimeSample is 09:40, not 07:40. Again change should happen in dateTimeSample and sampleID.

**Comment by ctsolomon** [comment]
Changes to dateTimeSample will propagate not only to sampleID, but also to fishID. Possibly onward from there to otoliths or anything like that?

**Comment by cwbeltz** [comment]
@Randinotte is this an issue that is being corrected as part of your recent dateTimeSample effort? If not, I can tackle it.

**Comment by Randinotte** [comment]
@cwbeltz No, this won't be fixed with that recent work. It does look like an easy one to work on. FISH_SAMPLES (sample table) is related to FISH_INFO (data table). So if the sampleID changes in FISH_SAMPLES, all rows in FISH_INFO with that sampleID will also need to be edited. As explanation, fishing "sampling events" are listed as a single row in FISH_SAMPLES. All the fish from that sampling event are listed in FISH_INFO with that sampleID. Each individual fish gets a fishID, which is just the sampleID + "_#" (for the number fish from that sampling event). 

So, to fix this issue, you'll need to:
1) Edit the sampleID and dateTimeSample columns in FISH_SAMPLES for both problem sampleID's given above (2 rows).
  - Change the updateID for these rows to indicate that it's been edited.
2) Edit the sampleID's and fishID's in FISH_INFO that correspond to these two sampleID's (47 and 51 rows, respectively).
  - Change the updateID for all rows to indicate that it's been edited. 
5) Create new tables (FISH_SAMPLES and FISH_INFO) and incorporate them into your db update. 

```
fs<-dbTable("FISH_SAMPLES")
fs_prob<- fs %>% filter(sampleID%in%c("WL_WholeShoreline_20170521_1230_BE_MarkRecap.20120228",
                                      "EL_WholeShoreline_20120612_0740_AN_MarkRecap.20120228"))

fi<-dbTable("FISH_INFO")
fi_prob<- fi %>% filter(sampleID%in%c("WL_WholeShoreline_20170521_1230_BE_MarkRecap.20120228",
                                      "EL_WholeShoreline_20120612_0740_AN_MarkRecap.20120228"))
fi_prob %>% group_by(sampleID) %>% count()
```

**Comment by cwbeltz** [comment]
Thanks @Randinotte! It didn't look like your updated overlapped, but I wanted to confirm. I will add this to my update this week.

**Comment by cwbeltz** [comment]
> Changes to dateTimeSample will propagate not only to sampleID, but also to fishID. Possibly onward from there to otoliths or anything like that?

@ctsolomon this does propagate to 21 records in FISH_OTOLITHS. Will fix those fishIDs as part of the larger fix of dateTimeSample.

**Comment by cwbeltz** [comment]
DB update this fix this issue approved by @ctsolomon at our weekly meeting on December 22. 

This update touches on FISH_SAMPLE, FISH_INFO, and FISH_OTOLITHS.

1. FISH_SAMPLE
- 2 records modified
- Time altered by 2 hours in sampleID and dateTimeSample
- Tz set to “America/Chicago” 

2. FISH_INFO
- 98 rows modified
- SampleID updated case_when()
- fishID updated via gsub on _DATE_TIME_

3. FISH_OTOLITHS
- 21 records modified
- Get problematic fishIDs from FISH_INFO and then modify fishIDs in FISH OTOLITHS.
- sampleID not included in FISH_OTOLITH table.
- fishID updated via gsub on _DATE_TIME_

**Comment by cwbeltz** [comment]
@ctsolomon Additional issue encountered with fishIDs in FISH_DIETS while running relationalChecks. Those issues are now corrected using a similar fix as those for FISH_OTOLITHS. The corrections for FISH_DIETS are:

4. FISH_DIETS
30 rows modified
Get problematic fishIDs from FISH_INFO and then modify fishIDs in FISH_DIETS.
sampleID and dateTimeSample not included in FISH_DIETS table.
fishID updated via gsub on DATE_TIME

Will make update once approved.

**Comment by cwbeltz** [comment]
Update completed on 2022-01-10 as part of database update 5.2.2.
