### ISSUE TITLE
fishNum jumbled in FISH_INFO for a 2010 sample

### ISSUE THREAD

**Issue by ctsolomon** [MFEh2o/db#169]
For sampleID=LO_WholeShoreline_20100624_1900_AN_MarkRecap.20120228, the fishNum entered in the database don't match those on the field data sheet. The data seem correct (with one exception, see below), it's just that the fish numbers don't match up. I'm attaching photos of the data sheets (2 pages), and also a spreadsheet showing how to match up the fishNum from the database with the fishNum from the data sheets.

The one bit of data that seems incorrect (other than the jumbled fishNum) is that the database gives a pitApply of 177417935 for the fish with floyRecap 2008-265, whereas the data sheet does not indicate this pitApply. Not clear to me yet how that error got in.

Note that I'm not entirely sure we need to fix the jumbled fishNum - it may be simpler just to add a comment to that sample in FISH_SAMPLES, warning people that trying to match the fishNum back to data sheet won't work in this case
[fish numbers for sampleID LO_WholeShoreline_20100624_1900_AN_MarkRecap.20120228.xlsx](https://github.com/MFEh2o/db/files/7716177/fish.numbers.for.sampleID.LO_WholeShoreline_20100624_1900_AN_MarkRecap.20120228.xlsx)
![Image from iOS (6)](https://user-images.githubusercontent.com/8375012/146115095-fd548847-0fe0-40e3-ab4d-3da546efb825.jpg)
![Image from iOS (5)](https://user-images.githubusercontent.com/8375012/146115098-9008c462-cec5-46e2-8cf8-df148c916389.jpg)
.

**Comment by cwbeltz** [comment]
@ctsolomon @joneslabND This issue was just discussed at 2022-02-23 meeting. The following changes will be made:
1a) jumbled fish numbers will be corrected using the Excel worksheet provided in the original issue. 
1b) changes to fish numbers will then be propagated into the rest of the fish database as needed.
2) pitApply number will be removed and I will note in the update metadata that pit tags were not applied until 2011.

Additional, we'll trace back the pitApply number as much as possible to identify when it was added to the database. To do this I'll check pit and floy numbers, follow updateID, and load older versions of the database.

**Comment by cwbeltz** [comment]
addressed as part of update to v5.3.3.
