### ISSUE TITLE
SED TRAPS new table

### ISSUE THREAD

**Issue by katiesaunders** [MFEh2o/db#25]
Create a table for sediment trap data.

**Comment by kaijagahm** [comment]
Reached out to Brittni about this; she'll get back to me when she has time.

**Comment by kaijagahm** [comment]
Notes from call with Brittni, Friday 6/26: Sending field and lab protocol. Have long cylinder traps that sit at the bottom of the lake. Deploy in 2-week increments. Need to quantify data in terms of deployment length (it's a rate). Rate at which carbon/sediment in the water falls to the ground. SetTime and retrievalTime gives you deployment length. Deployment length is a bit variable. After two weeks, collect all the material, filter it down into little circular filters. Filter a subset of what's in the trap. For data: get Carbon, Nitrogen, and Phosphorus values for the filter. Have to multiply by the total volume of water that was filtered to get the total amounts (bc it was just a subset).

**Comment by kaijagahm** [comment]
@brittnibertolet I've started looking through this and have a few questions about certain columns. For brevity, I'm going to refer to the csv's by their years here.

1. There's a column sampleID in 2013 and 2014: integers, not in order, with some missing. Is this the same as the Sample column in 2015, 2017, and 2018 (integers, in order, looks fairly complete)? Any idea why we don't have a similar column in 2016? Should I be concerned that 2013 and 2014 are out of order and seem to be missing some numbers?

2. In 2018, there are three columns called "quarterFilter", one for each of C, N, and P. Can you explain what those are? Since they don't exist in the other years, should I remove them from 2018, or should I leave them in and just set them to NA for the other years?

3. There's a "flag" column in 2013 and 2014, but not in the other years. It's set to 0 in all rows of both 2013 and 2014. My guess is that this was a quality control thing, and any rows that were flagged ended up being removed, which would explain both the fact that none of the current rows are flagged and the missing sampleID's in those two tables. Am I right? Any reason not to remove this column now?)

4. There's a column "Rep" in 2013, but not in any other years. It has integer values 1-4. Do you know what this is, and what I should do with it?

Thank you!

**Comment by kaijagahm** [comment]
Made all the name changes that I can for now--most names are now standardized, with the exception of the above questions, the sampleID's, and the uniqueID's.

**Comment by kaijagahm** [comment]
Some updates from Randi:

1. Randi says these are probably numbers that were assigned by the machine, and they don't make much sense out of context. Can likely be removed. When they're out of order/have numbers missing, that probably means that control samples have already been removed from those years.

2. Need to check whether the values in the quarterFilter columns are exactly 1/4 of the values in the regular N_mg (etc) columns. If so, that's probably how those were calculated--though maybe @brittnibertolet can confirm? Still not sure, if this is the case, whether we should keep those columns in the database table and set them to NA for the other years or remove them.

3. Probably refers to quality control--apparently other db tables also have a "flag" column. Probably can leave it in, and set to NA for those that don't already have a "flag" column.

4. Rep probably has to do with the quarterFilter column? Not sure what to do with it.

5. Randi thinks these are probably different comments for e.g. lab, field, etc. Can probably be pasted together, separated by a semicolon or something.

**Comment by kaijagahm** [comment]
Stuart suggests using "point" for the depthClass here.

**Comment by brittnibertolet** [comment]
1. I agree with Randi that these were likely generated during sample processing as a unique identifier with the order simply determined by the order in which the filter was picked from the box and placed in the autosampler. Then, in these csvs, Jake ordered the rows by lake ID and deployment, which is why they are now out of order. I do think we want to keep this unique identifier though, for the event in which we ever wanted to go back to the raw machine output. I think condensing it across all years into a single column works. And yes, 2016's Filter.ID would be the same column. 

2. Did you check whether the values in the quarterFilter columns are exactly 1/4 of the values in the regular N_mg (etc) columns? If so, then yes, I think it's likely that only 1/4th of the filter was analyzed and then we multiply the concentration up to estimate the full filter. The question is then, do we always do this or did we only do this in 2018? I'm not sure.. We should ask Stuart. If we always did this, then we could remove the column as the other csvs don't have it. If this was only done in 2018, then I think we need to keep the column to indicate that it was a subset estimation. 

3. I think usually we keep the flag column.

4. No idea about this one, sorry. Maybe Stuart knows. The ecological replication is indicated by the trapID, so I think it's correct to assume this is probably technical replication during analysis, but I'm not sure what to do with it. 

5. Yup, can be collapse to one comments column! Semi-colon is probably best.

**Comment by kaijagahm** [comment]
2. I checked, and the values in the quarterFilter columns are **not** 1/4 of the values in the regular columns. Sometimes they are, almost exactly (e.g. C_mg/4 = 0.5582806, quarterFilterC_mg = 0.55828060), but more often they are so far off that it's unrecognizable. For example, here are the first 9 values of quarterfilterC_mg: 

`0.73719666 0.58847108 0.33627702 0.55828060 0.32652252 0.43499523 0.24658514 0.34630036 0.39443395`

and here are the first 9 values of C_mg/4
`2.0477685  1.2554050  0.7532605  0.5582806  0.7836540  1.2237866  0.7430432  0.7941822  1.0623421`

**Comment by kaijagahm** [comment]
quarterFilter might have been portions of the large filter being run separately. Check to see if there are multiple replicates from 2018.

Leaving depthBottom and depthTop as NA for now--better ideas?

Removed deployID--can be derived from dates. Removed DeepHole as siteID and used the trapID as the siteID instead. Creating a new table for samples--SED_TRAP_SAMPLES--and then probably putting the data in either POC or NUTRIENTS.

The first question is whether we want to keep all four columns for each nutrient: *_mg, *_mg_m2, *_mg_m2_day, and *_mmol_m2_day. We have information about totalVolmL and volFilteredmL, so we could recreate the concentration. But I'm not sure where the m2 is coming from. There's no information in the metadata file about m2 or area. If we had some sort of area measurement, then all of these measurements would be possible to derive just from *_mg, so we wouldn't have to worry about including all of them.

Two scenarios: NUTRIENTS and POC.
1) NUTRIENTS has columns "parameter" and "parameterValue". So if we were adding the data to there, we'd have to use the existing parameters (TP, TN, particulateP, SRP, and nitrate) or add new ones. I'm a little foggy on the chemistry of all of this--would these existing parameters work for the P and N sediment trap samples?

2) If we add the samples to POC, then we'd be using the POC and PON columns. It looks like those are measured in mg/L, so it shouldn't be hard to convert our sed trap values. I don't know what we would do about the per day values--see above. We would have to add a POP column, but #9 will already have us the particulateP samples over from NUTRIENTS to POC, so I think we're going to have to create a POP column anyway.

Side note: should we rename the POC table to indicate that it has N and P measurements as well?

**Comment by ctsolomon** [comment]
Re depthBottom and depthTop - Should be the case that the depth these were deployed at is recorded somewhere, yes? If it needs to go in one of those columns, I think there's a standard we use - like maybe we always use depthBottom when it only makes sense to list one depth?

Re removing deepHole from siteID - I think maybe we talked about this, but confirming: it will still be clear somewhere (metadata or something) that these were deployed at deep hole, correct?

Re which columns to keep - I would check with Stuart or Carly or someone. I think all of the per area and per day columns could be re-derived from the regular mg column - area sampled is known and constant (and should be in metadata or a column), days sampled presumably is in the deployment info somewhere. So most streamlined approach would be just to keep mg, and then put a script in our utilities repo that lets one calculate the other stuff.

Re where to put the data - The POC table seems attractive given that it already has POC and PON data and I guess will soon have POP data. But the units issue concerns me - the sed trap data aren't concentrations per volume but rather rates per area, and I don't think we want to mix those in the same column. Create new columns? Create new table for sed trap data?

**Comment by joneslabND** [comment]
depthBottom and depthTop - if this is in the sed_trap_sample table it makes sense to actually put the trap depployment depth and if it is a point (like the traps) we put the same depth in both depthTop and depthBottom

add deepHole deployment and area of traps to metadata

the units are an issue.... I guess I had forgotten or not realized that we back calculate the volumetric concentration for POC and PON. Is there not a column with the mass on the filter? If there was, we could use this for sed trap data and leave the concentration column blank...

**Comment by kaijagahm** [comment]
> Should be the case that the depth these were deployed at is recorded somewhere, yes?
I hope so? I can't find this information. The metadata describes how to deploy the traps, and mentions that the rope length has to be adjusted to the depth of the lake, but it doesn't specify any exact depths, nor does it note the distance between the bottom weight and the trap itself.

> add deepHole deployment and area of traps to metadata
Metadata does already say that traps were deployed at (well, very near) the deepHole. Area of traps is not in the metadata--do we have that information somewhere?

> Is there not a column with the mass on the filter? If there was, we could use this for sed trap data and leave the concentration column blank...
In POC? No, there is not a mass column. Given that, what do you think we should do?

**Comment by kaijagahm** [comment]
I got trap size measurements from Colin and Camille.

> Internal diameter 4 & 1/16th in or 10.3 cm
> Cylinder length is 17.25 inches
> Small piece 5 1/2 inches
> Last piece 17 inches

Colin also says: 

> we couldn't get inner diameters on the last two items without taking them apart, the small piece that funnels into the last piece. Somewhere, I believe on OneDrive, the instructions for making these exist, presumably the dimensions of all the pieces should be listed there too, that's a better question for Brittni or Carly though.

Mainly all that we need is that inner diameter so we can calculate area. Just a back-of-the-napkin calculation here: pi*r^2 = pi*(10.3cm/2)^2 = pi*26.5225cm2 = **83.32cm2**

We've decided at meetings to create *two* new sediment trap samples tables: SED_TRAP_SAMPLES and SED_TRAP_DATA or something like that. Justification for separate SED_TRAP_SAMPLES is that we need dateTimeSet and dateTimeSample like we have for FISH_SAMPLES, so that won't fit in with the structure of SAMPLES. Justification for separate SED_TRAP_DATA: I'm a little foggier on the explanation for this, but basically because of the way the samples are taken they end up being measured in different units than the other nutrient samples. The concentrations aren't per L of lake water, they're something else based on how much was filtered...

**Comment by kaijagahm** [comment]
Have now created SED_TRAP_SAMPLES and SED_TRAP_DATA. Only question remaining is how many of the SAMPLES-related columns to also include in the DATA table, e.g. following the WATER_CHEM paradigm vs. the FISH_INFO paradigm. I have done the latter for now. Will discuss at 9/30 meeting.

**Comment by kaijagahm** [comment]
Created SAMPLES and DATA tables, using the more parsimonious column format. Wrote to file. Ready for database update. Also need to update the METADATA table, which I'll do in the meta document.

**Comment by kaijagahm** [comment]
Closed with db version 3.5.0, 9/30/2020
