### ISSUE TITLE
ZOOPS appearance of calanoids

### ISSUE THREAD

**Issue by joneslabND** [MFEh2o/db#4]
Calanoids were really abundant in 2018 and fairly rare earlier. Need to double check this with some spot checks or recounts...

**Comment by Randinotte** [comment]
We settled this, and could probably call it closed. Calanoids became abundant in 2018 due to Matt's incorrect subsetting technique and suspected mis-identification of meso-cyclops cyclopoids. Randi removed the erroneous data (all zoops samples from 2018) and replaced them with the recount values from Randi and Amaryllis in 2019.
