### ISSUE TITLE
WATER_CHEM merge POC, NUTRIENTS, DOC

### ISSUE THREAD

**Issue by joneslabND** [MFEh2o/db#9]
filter volume is going to have to be found in the logs to do this and the numbers in the nutrients table are derived and we need back calculate to mass on filter...

**Comment by katiesaunders** [comment]
We will need the filter volume, but we could match the sample info for particulateP to sample info in the POC table since they will all have the same filter volume for each sample (rather than trying to go through old logs). We also shouldn't need to back calculate to mass since the POC/PON values are also derived and reported as concentrations. So this might not be *too* difficult, if we want to make this change.

**Comment by kaijagahm** [comment]
Following Katie's suggestion, I've taken a look at this data. Unfortunately, while some of the particulateP sampleID's are already in POC, 158 of them are not. I'll have to look back at the logs for those. All of them are present in SAMPLES, but SAMPLES doesn't have filter volumes recorded.

**Comment by kaijagahm** [comment]
Some of these data sheets may be on OneDrive, and some may be physical copies at ND

**Comment by kaijagahm** [comment]
POP in the POC table? Does that even make sense? POC and POP were analyzed in totally different ways, and the POP data is the same analysis method as the nutrients.

**Comment by kaijagahm** [comment]
Randi and I traced one of the particulateP sampleID's that was in NUTRIENTS but not in POC: WL_DeepHole_20110727_0940_Hypo_1_Limno.Sample.20110517. We noted that it's weird to have a Hypo sample with depth 1. We looked through the sampleID's in POC and found a sampleID with depth 8m that was otherwise identical to this one. Perhaps a mistake? Then looked in SAMPLES and found that both sampleID's (1 and 8) were present, with NA's in most of the columns for the 8m one, and information for the 1m one. What's going on? Could these other sampleID's have similar problems? Going through them one by one probably isn't useful.

We could look into this sampleID by sampleID, but that probably isn't the most productive way of going about it. We talked, and think that the best thing to do is 1) wait until we've resolved the sampleID inconsistency issue first. 2) Propagate those changes from SAMPLES and FISH_SAMPLES out to all of the other tables. 3) in each other table, try to re-create the sampleID's as well. If we run into problems, determine whether it's an issue with the information in that table, with the information in SAMPLES/FISH_SAMPLES, or both. Then go from there.

**Comment by kaijagahm** [comment]
Leaving the sampleID issue aside here for a second, updates on this: 
At 9/22 meeting we [SEJ, CTS, RN, KG] decided to put all the nutrient/water chem tables together into one, called WATER_CHEM. This will include NUTRIENTS, POC, and DOC (but not CHLOROPHYLL, at least not yet).

Some notes on this:
- @Randinotte says this shouldn't affect data import too badly because NUTRIENTS is already assembled from data from several different machines/sources. Can continue being a piecemeal import.
- We'll generally use the parameter/value format to combine the tables. Can add a "units" column if we need one, to differentiate between different units for different parameters. But Chris thinks we might not need one--all might already be in the correct units.
- Will need to average the DOC replicates. @kaijagahm will also take a look at the % difference between replicates and make a histogram to try to establish a cutoff percentage for flagging those samples.
- We'll move the raw DOC data to a folder, along with a script to do the averaging. In the future, we can add line to the DOC processing script that will average the data before it comes in.
- @kaijagahm will make a draft of this table and note what issues arise.

Note from Kaija: I had actually forgotten about this sampleID weirdness at the 9/22 meeting. Indicates that we might end up having trouble merging these tables. We'll see.

**Comment by kaijagahm** [comment]
> filter volume is going to have to be found in the logs to do this and the numbers in the nutrients table are derived and we need back calculate to mass on filter...

I think @joneslabND's original take on this issue isn't quite right--we don't need to back-calculate masses unless it's very important to have mass information recorded instead of concentration for some reason.

**Comment by kaijagahm** [comment]
@ctsolomon @joneslabND @Randinotte given the choice, do we want concentration values for DOC, NUTRIENTS, and POC to be in ug/L or mg/L? Currently, some db tables use one and some use the other. Conversion's easy, just wondered if you have a preference.

**Comment by ctsolomon** [comment]
I dunno...ug I guess unless Stuart or Randi prefer mg. But - if the table is in long format and we have a units column (am I remembering that correctly?), couldn't we just put each analyte in its most sensible unit?

**Comment by kaijagahm** [comment]
We had decided to leave off the units column because it seemed like they could all be in the same format, since they're all concentration. But if we care deeply about ug vs mg for the different analytes, I can add a units column.

**Comment by joneslabND** [comment]
Let's stick with no units column.  ug is probably better to avoid really small numbers for P concentrations

**Comment by kaijagahm** [comment]
Roger. That's what I had done anyway, so glad to hear you're on the same page.

**Comment by kaijagahm** [comment]
This is in pretty good shape, but waiting for DOC.

**Comment by kaijagahm** [comment]
DOC QC is finished. Script is DOC_QA_QC_funs.R (functions for processing--useful for past and future data), stored on the GH. Also DOC_QA_QC.R: this is the actual processing of old data.

Still need to deal with the few cases where there were more than 2 replicates for a single sampleID, and tack that result onto the end. Then the data will be ready to add to WATER_CHEM.

Note that the newly-created QCcode column won't have a value for the non-DOC data in WATER_CHEM, but that's okay.

Randi is going to give me the 2020 DOC data to process in the same way, shortly.

**Comment by kaijagahm** [comment]
Emailed RN, CTS, SEJ to check for metadata on the bioassay 2011 project, because one of the sampleID's with four replicates is from that.

**Comment by kaijagahm** [comment]
Removed samples with "Bioassay" comment. Checked raw data against bioassay 2011/2012 datasheets to make sure there wasn't any unlabeled bioassay data still in the table--there wasn't. Resolved the one remaining set of multiples--took average, checked for OOB, flagged as code12. 

Have written out new DOC data. Need to read it back into WATER_CHEM and prepare that table for final write-out.

**Comment by kaijagahm** [comment]
Added to version 4.0.0

**Comment by kaijagahm** [comment]
Cleaning out my google drive: here's a file that was used to parse through comments on the DOC measurements and decide whether to take action on them. 
[DOC comments.xlsx](https://github.com/MFEh2o/db/files/6679390/DOC.comments.xlsx)
