### ISSUE TITLE
fishEntryTool notes

### ISSUE THREAD

**Issue by Randinotte** [MFEh2o/db#98]
The current *SAMPLES to *INFO format is that all sampling events are included in *SAMPLES, even when no fish are caught (NFC). Then, only real observations are included in *INFO. This means that there may/will be sampleIDs in *SAMPLES with no matching samples in *INFO. 

During an update of FISH_SAMPLES and FISH_INFO for 2019 and 2020, I found that the 2019 fishscapes fishSamplesIS.csv and 2020 Jones Lake fishSamplesIS.csv only included sampleID's that were found in their fishInfoIS.csv. This leads me to believe that fishSamplesIS.csv does not include NFC samples, or possibly that there were no cases of NFC at all in 2019 fishscapes or the 2020 Jones Lake experiment. 

When we begin work on the fishEntryTool, can we check if this is the case on the most recent version? It would be great to have fishSamplesIS including ALL samples before the start of the 2021 field season.

**Comment by Randinotte** [comment]
Changed the title to be more broadly about the fishEntryTool.

**Comment by Randinotte** [comment]
Camille's raw csv files had 21 duplicate files with only changes in filename spelling (eg. 2020-06-24 and 2020_06_24). It seems that this would be a problem of bad input not bad output, but having the tool check for duplicates might be helpful? I spent over an hour trying to track down non-matching dimensions. There were no duplicate fishIDs on these 21 samples, so the entry tool was seemingly able to catch that at least.

**Comment by Randinotte** [comment]
entry tool created the dates"0020716" and "00200717" instead of 2020-07-16 and 2020-07-16. These were in the fishSamplesIS.csv and fishInfoIS.csv from 2020 Jones Lake, so the date issue existed as output from the entry tool before I started working with it. In an ideal world, the entry tool shouldn't create dates that don't exist.

**Comment by Randinotte** [comment]
Some column names in the output don't match the db tables. Pluralized, spelling, etc. "otolithSample" vs. "otolithSampled"

**Comment by kaijagahm** [comment]
Add more descriptions to the warning messages, telling you what will happen if you use the `force` arguments instead of just telling you to use them.

Model this after the DOC tool, where it says "force is TRUE, so we will do X"

**Comment by kaijagahm** [comment]
Entry tool is going pretty well. I'm running it through old data to find any mistakes and make whatever tweaks are necessary.

Outstanding problems/special cases that I'm not sure how to deal with:
- fishScapes2019_LT_2019-07-22_2355.csv is a BE sheet, but it's missing distanceShocked. That seems to be intentional. There's a comment ''Map my run did not restart so distance not accurate but time is and stopped at 2 boat piers along leaner shoreline opposite boat launch USE TIME CPUE BUT NOT DIST". How would we handle that case? Currently, the tool requires distanceShocked for any BE samples, and it seems like a pain to add an option to force that. So would we enter 0, or something else? There's no useDistanceShocked parameter...

**Comment by kaijagahm** [comment]
I updated the entry tool to allow NA for distanceShocked.
